# Generated by Django 5.1.3 on 2024-11-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(blank=True, help_text='Author of the book', max_length=255, null=True),
        ),
    ]
