# Generated by Django 5.1.3 on 2024-11-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_product_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='billboard_images/')),
                ('link', models.URLField(blank=True, help_text='Optional link for the billboard item', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active items are displayed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Billboards',
                'db_table': 'billboard',
                'ordering': ['-created_at'],
            },
        ),
    ]
