# Generated by Django 5.1.3 on 2024-11-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_product_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
