# Generated by Django 5.1.4 on 2025-01-09 05:21

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cart",
            options={"verbose_name_plural": "Cart Items"},
        ),
        migrations.AlterModelOptions(
            name="cartorder",
            options={"ordering": ["-created_at"], "verbose_name_plural": "Cart Orders"},
        ),
        migrations.AlterModelOptions(
            name="cartorderitem",
            options={"verbose_name_plural": "Cart Order Items"},
        ),
        migrations.AddField(
            model_name="cart",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="cartorder",
            name="order_id",
            field=shortuuid.django_fields.ShortUUIDField(
                alphabet="abcdefgh12345",
                length=10,
                max_length=20,
                prefix="ORD",
                unique=True,
            ),
        ),
    ]
