# Generated by Django 5.1.4 on 2025-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_alter_cart_options_alter_cartorder_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartorderitem",
            options={},
        ),
        migrations.AlterField(
            model_name="cartorderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name="cartorderitem",
            table=None,
        ),
    ]
