# Generated by Django 5.1.4 on 2025-01-11 05:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_aboutsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutsection",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="aboutsection",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
