# Generated by Django 5.1.4 on 2025-01-11 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_aboutsection_created_at_aboutsection_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
