# Generated by Django 5.1.5 on 2025-01-24 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_remove_book_category_book_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="library",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="library",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libraries",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="book",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="libraries",
                to="core.book",
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="library",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="library",
            unique_together={("user", "product")},
        ),
    ]
