# Generated by Django 5.1.5 on 2025-01-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_library_unique_together_library_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="epub_file",
            field=models.FileField(
                blank=True, null=True, upload_to="protected_ebooks/"
            ),
        ),
    ]
