# Generated by Django 5.1.6 on 2025-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_alter_product_epub_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="epub_file",
        ),
        migrations.AddField(
            model_name="product",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="protected_pdfs/"),
        ),
    ]
