# Generated by Django 5.1.6 on 2025-03-21 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
