# Generated by Django 5.1.6 on 2025-03-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_blog_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="slug",
        ),
    ]
